#! /usr/bin/env python
import sys, glob
from subprocess import Popen, PIPE
from os import listdir
from os.path import isfile, join
orig_algn = []

try:
    if sys.argv[1] == '-dir':
        testdir = sys.argv[2]
        orig_algn = [join(testdir,f) for f in listdir(testdir) if isfile(join(testdir,f)) and f.endswith('.msl')]                
    else:
        for i in range(1, (len(sys.argv))):
           orig_algn.extend(glob.glob(sys.argv[i]))

except IOError as e:
    print e
    print >> sys.stderr , 'ERROR! Must be:'
    print >> sys.stderr , './evaluate [-dir directory] [multialignment files]'

#print orig_algn
reduced_algn = [ (f+'.reduced') for f in orig_algn ]
#print reduced_algn
for i in range(len(orig_algn)):
    cmd= './reducenoise.py -in '+orig_algn[i]+ ' -out ' + reduced_algn[i]
    p=Popen(cmd,shell=True,stdout=PIPE)
    p.wait()
