#! /usr/bin/env bash
dir=$(date +"%Y%m%d%H%M")
mkdir ../results/$dir
./evaluate -dir ../data/symmetric_0.5 > ../results/$dir/symmetric_0.5
./evaluate -dir ../data/asymmetric_0.5 > ../results/$dir/asymmetric_0.5
./evaluate -dir ../data/symmetric_1.0 > ../results/$dir/symmetric_1.0
./evaluate -dir ../data/asymmetric_1.0 > ../results/$dir/asymmetric_1.0
./evaluate -dir ../data/symmetric_2.0 > ../results/$dir/symmetric_2.0
./evaluate -dir ../data/asymmetric_2.0 > ../results/$dir/asymmetric_2.0

./updateSQL.py -in ../results/$dir/symmetric_0.5 -out ../results/$dir/database.db
./updateSQL.py -in ../results/$dir/symmetric_1.0 -out ../results/$dir/database.db
./updateSQL.py -in ../results/$dir/symmetric_2.0 -out ../results/$dir/database.db
./updateSQL.py -in ../results/$dir/asymmetric_0.5 -out ../results/$dir/database.db
./updateSQL.py -in ../results/$dir/asymmetric_1.0 -out ../results/$dir/database.db
./updateSQL.py -in ../results/$dir/asymmetric_2.0 -out ../results/$dir/database.db
